"""add team name and members

Revision ID: 3e3a64950a2f
Revises: d91bcd3b763a
Create Date: 2026-02-24 12:35:46.485530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3a64950a2f'
down_revision = 'd91bcd3b763a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_user',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('especial')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        # foreign key constraints will be created below; skip unnamed drop
        batch_op.create_foreign_key(None, 'meeting', ['meeting_id'], ['id'])
        batch_op.create_foreign_key(None, 'region', ['region_id'], ['id'])
        batch_op.drop_column('event_id')
        batch_op.drop_column('criado_em')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'region', ['region_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # drop foreign key to region if exists
        pass

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        # unnamed foreignkey drops removed
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_column('region_id')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especial', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("('')"))

    op.drop_table('team_user')
    # ### end Alembic commands ###
