"""add special flag and team table

Revision ID: d91bcd3b763a
Revises: ca2239ce24c3
Create Date: 2026-02-24 10:35:08.318339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd91bcd3b763a'
down_revision = 'ca2239ce24c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # previously dropped team_member table; no-op for sqlite
    # op.drop_table('team_member')
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special', sa.Boolean(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        # drop_constraint may not exist on sqlite, ignore if so
        # batch_op.drop_constraint(batch_op.f('team_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'region', ['region_id'], ['id'])
        batch_op.create_foreign_key(None, 'meeting', ['meeting_id'], ['id'])
        batch_op.drop_column('nome')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criado_em', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nome', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_ibfk_1'), 'event', ['event_id'], ['id'])
        batch_op.drop_column('region_id')
        batch_op.drop_column('meeting_id')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('special')

    op.create_table('team_member',
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('team_member_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('team_member_ibfk_2')),
    sa.PrimaryKeyConstraint('team_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
